site_name: Blockscape
site_url: https://pwright.github.io/blockscape/

docs_dir: docs
site_dir: ../docs/documentation

nav:
  - Home: https://pwright.github.io/blockscape/
  - Hello: documentation/tipping.md
  - Maps:
      - Blockscape Example: maps/blockscape-example.md
      - Wardley Example: maps/wardley-example.md
      - Series Example: maps/series-example.md
  - Documentation:
      - Overview: documentation/maps.md
      - Features: documentation/features.md
      - Series: documentation/series.md
      - Models: documentation/models.md
      - Build patterns: documentation/build-patterns.md
      - LLM generation: documentation/llm-generation.md
      - Evolution: documentation/evolution.md
      - Gestalt: documentation/gestalt.md
      - Gists: documentation/gists.md
      - Icons: documentation/icons.md
      - LLM consume: documentation/llm-consume.md
      - JSON prompting: documentation/rise-and-fall-json.md
      - Navigation: documentation/navigation.md
      - Paste: documentation/paste.md
      - Portfolio: documentation/portfolio.md
      - Relational awareness: documentation/relational-awareness.md
      - Share links: documentation/share-links.md
      - Stages: documentation/stages.md
      - Value chain: documentation/value-chain.md
      - Watch models: documentation/watch-models.md
  - Integrations:
      - Obsidian plugin: documentation/obsidian.md
      - MkDocs usage: documentation/mkdocs.md
      - Apicurio as backend: documentation/apicurio.md
      - Docker for local editor: documentation/docker.md
      - Local usage on Linux: documentation/bs-opener-linux.md
      - Local usage on Mac: documentation/bs-opener-mac.md
      - Local backend server: documentation/server.md
      - Desktop app (Linux and macos): neutralino-app.md
  - TOC: toc.md

markdown_extensions:
  - mkdocs_blockscape.extension

extra_css:
  - site_assets/blockscape/blockscape.css

extra_javascript:
  - site_assets/blockscape/blockscape.js
  - site_assets/blockscape/mount.js
